/** Product context and evidence priorities for the initial discussion Forum. */
export const COLORS_FORUM_MEMBERSHIP_OBJECTIVE =
  "Get to know why someone wants to join the COLORS Forum, their existing connection to COLORS and music, how they take part in communities, and what they hope to find or bring to this one."

export const COLORS_FORUM_MEMBERSHIP_CONTEXT =
  "The initial Forum is for discussion and sharing external links; it does not support audio uploads. It will have space for TONES and live events. Approved TONES description: TONES is a COLORS series of live events spotlighting a city and its community, including artists, small businesses, brands and local people. The Forum will have space for TONES and live-event conversations. Do not reduce TONES to listening-only events or say the events happen alongside the Forum. Do not invent details of a particular event, schedule, venue, lineup or the applicant's attendance."

export const COLORS_FORUM_MEMBERSHIP_REVIEW_GUIDANCE = `This is an initial membership conversation for an online discussion Forum. Assess the applicant's stated reasons for joining, their relationship with COLORS, their relationship with music as a listener, maker or participant in a scene, how they show up in online or offline communities, and the kind of participation they hope for here. Treat a concrete offline community practice as equally useful evidence of community participation. Look at what the person says they do with others, not the medium or size of the group. A concrete account of learning from a different musical perspective can show how they take part; do not require agreement or a hypothetical disagreement test. A wish to read, discuss, share public links, make music or join TONES and live-event conversations may all be useful participation context. Do not equate value with posting frequency, professional status or attending events.

Familiarity with a particular COLORS show or artist is welcome context, not a knowledge test. TONES awareness or first-hand experience may enrich the profile, but lack of awareness or attendance is neutral and must never become a reservation, material gap, lower confidence by itself, or reviewer question. Attendance depends on access and location. Never invent TONES event details. Describe an existing community practice as existing practice; do not turn it into a specific Forum plan unless the applicant states that plan. The initial Forum supports discussion and external links, with no audio uploads. Sharing or recommending publicly available music and links does not require an artist-permission declaration and is not a negative fit signal. Do not use an applicant's uncertainty about a broad permission hypothetical as a concern. Only independently stated intent to expose someone else's private material or other concrete harmful conduct may be considered under the separate safety boundary.`
